# Application
spring.application.name=ecommerce-demo

# Active Profile (local, dev, prod)
spring.profiles.active=local

# JPA Common
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate UTF-8 설정 (모든 환경 공통)
spring.jpa.properties.hibernate.connection.characterEncoding=utf8mb4
spring.jpa.properties.hibernate.connection.useUnicode=true

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Logging
logging.level.root=INFO
logging.level.com.example.ecommercedemo=DEBUG
